#include "helper.h"
#include "visual.h"
#include <stdio.h>


#define B_N 2          
#define B_S 1             // Defining the values to find boundary directions. 
#define B_W 4
#define B_E 8
#define B_NE 9
#define B_NW 5
#define B_SE 10
#define B_SW 6


void write_vtkFile(const char *szProblem,
		 int    timeStepNumber,
		 double xlength,
     double ylength,
     int    imax,
     int    jmax,
		 double dx,
		 double dy,
     double **U,
     double **V,
     double **P,
     int** FLAG)

{

for (int i = 1; i <=imax; ++i)
  {
    
    for (int j = 1; j <=jmax; ++j)
    {
    //printf(" boundaryvalues %d  %d \n", i, j);
      if (FLAG[i][j] >=1 && FLAG[i][j] <=15)
      {
        if (FLAG[i][j] == B_E)
        {
          U[i][j] = 0;
          V[i][i-1] = 0;
          V[i][j] = 0;
          P[i][j] = 0;

        }
        else if (FLAG[i][j] == B_W)
        {
          U[i-1][j] = 0;
          V[i][j-1] = 0;
          V[i][j] = 0;
          P[i][j] = 0;

        }
        else if (FLAG[i][j]  == B_S)
        {
          V[i][j-1] = 0;
          U[i][j] = 0;
          U[i-1][j] = 0;
          P[i][j] = 0; 
        }
        else if (FLAG[i][j]  == B_N)
        {
          V[i][j] =0;
          U[i-1][j] = 0;
          U[i][j] = 0;
          P[i][j] = 0;
          
        }
        else if (FLAG[i][j] == B_NE)
        {
          U[i][j] = 0;
          V[i][j] = 0;
          U[i-1][j] = 0;
          V[i][j-1] = 0;
          P[i][j] = 0;
        }
        else if (FLAG[i][j] == B_NW)
        {
          U[i-1][j] = 0;
          V[i][j] = 0;
          U[i][j] = 0;
          V[i][j-1]= 0;
          P[i][j] = 0;
        }
        else if (FLAG[i][j] == B_SE)
        {
          U[i][j] = 0;
          V[i][j-1] = 0;
          U[i-1][j] = 0;
          V[i][j] = 0;
          P[i][j] = 0;
        }
        else if (FLAG[i][j] == B_SW)
        {
          U[i-1][j] = 0;
          V[i][j-1] = 0;
          U[i][j] = 0;
          V[i][j] = 0;
          P[i][j] = 0;       
        }

      }
    }
  }








  int i,j;
  char szFileName[80];
  FILE *fp=NULL;
  sprintf( szFileName, "%s.%i.vtk", szProblem, timeStepNumber );
  fp = fopen( szFileName, "w");
  if( fp == NULL )		       
  {
    char szBuff[80];
    sprintf( szBuff, "Failed to open %s", szFileName );
    ERROR( szBuff );
    return;
  }

  write_vtkHeader( fp, imax, jmax, dx, dy);
  write_vtkPointCoordinates(fp, imax, jmax, dx, dy);

  fprintf(fp,"POINT_DATA %i \n", (imax+1)*(jmax+1) );
	
  fprintf(fp,"\n");
  fprintf(fp, "VECTORS velocity float\n");
  for(j = 0; j < jmax+1; j++) {
    for(i = 0; i < imax+1; i++) {
      fprintf(fp, "%f %f 0\n", (U[i][j] + U[i][j+1]) * 0.5, (V[i][j] + V[i+1][j]) * 0.5 );
    }
  }

  fprintf(fp,"\n");
  fprintf(fp,"CELL_DATA %i \n", ((imax)*(jmax)) );
  fprintf(fp, "SCALARS pressure float 1 \n"); 
  fprintf(fp, "LOOKUP_TABLE default \n");
  for(j = 1; j < jmax+1; j++) {
    for(i = 1; i < imax+1; i++) {
      fprintf(fp, "%f\n", P[i][j] );
    }
  }

  if( fclose(fp) )
  {
    char szBuff[80];
    sprintf( szBuff, "Failed to close %s", szFileName );
    ERROR( szBuff );
  }
}


void write_vtkHeader( FILE *fp, int imax, int jmax, 
                      double dx, double dy) {
  if( fp == NULL )		       
  {
    char szBuff[80];
    sprintf( szBuff, "Null pointer in write_vtkHeader" );
    ERROR( szBuff );
    return;
  }

  fprintf(fp,"# vtk DataFile Version 2.0\n");
  fprintf(fp,"generated by CFD-lab course output (written by Tobias Neckel) \n");
  fprintf(fp,"ASCII\n");
  fprintf(fp,"\n");	
  fprintf(fp,"DATASET STRUCTURED_GRID\n");
  fprintf(fp,"DIMENSIONS  %i %i 1 \n", imax+1, jmax+1);
  fprintf(fp,"POINTS %i float\n", (imax+1)*(jmax+1) );
  fprintf(fp,"\n");
}


void write_vtkPointCoordinates( FILE *fp, int imax, int jmax, 
                      double dx, double dy) {
  double originX = 0.0;  
  double originY = 0.0;

  int i = 0;
  int j = 0;

  for(j = 0; j < jmax+1; j++) {
    for(i = 0; i < imax+1; i++) {
      fprintf(fp, "%f %f 0\n", originX+(i*dx), originY+(j*dy) );
    }
  }
}


